In [1]:
import pandas as pd

In [4]:
df = pd.read_csv('laptops.csv')

In [10]:
brands_list = df['Brand'].drop_duplicates()

In [12]:
len(brands_list)

27

In [14]:
df.nunique()

Laptop          2160
Status             2
Brand             27
Model            121
CPU               28
RAM                9
Storage           12
Storage type       2
GPU               44
Screen            29
Touch              2
Final Price     1440
dtype: int64

In [17]:
df.isnull().sum()

Laptop             0
Status             0
Brand              0
Model              0
CPU                0
RAM                0
Storage            0
Storage type      42
GPU             1371
Screen             4
Touch              0
Final Price        0
dtype: int64

In [23]:
df_dell = df[(df['Brand'])=='Dell']

In [25]:
df_dell['Final Price'].max()

3936.0

In [27]:
median = df['Screen'].median()

In [37]:
median

15.6

In [30]:
freq = df['Screen'].mode()

In [38]:
freq

0    15.6
Name: Screen, dtype: float64

In [43]:
df['Screen'].fillna(freq)

0       15.6
1       15.6
2       15.6
3       15.6
4       15.6
        ... 
2155    17.3
2156    17.3
2157    17.3
2158    13.4
2159    13.4
Name: Screen, Length: 2160, dtype: float64

In [44]:
df['Screen'].isna().sum()

4

In [45]:
df['Screen'].median()

15.6

In [57]:
injo_df = df[df['Brand'] =="Innjoo"]
X = injo_df[['RAM','Storage','Screen']].to_numpy()

In [75]:
XTX = X.T @ X

In [62]:
import numpy as np

In [65]:
XTX = X@X.T

In [76]:
XTX

array([[2.52000e+02, 8.32000e+03, 5.59800e+02],
       [8.32000e+03, 3.68640e+05, 1.73952e+04],
       [5.59800e+02, 1.73952e+04, 1.28196e+03]])

In [81]:
XTX_inv = np.linalg.inv(XTX)

In [82]:
XTX_inv

array([[ 2.78025381e-01, -1.51791334e-03, -1.00809855e-01],
       [-1.51791334e-03,  1.58286725e-05,  4.48052175e-04],
       [-1.00809855e-01,  4.48052175e-04,  3.87214888e-02]])

In [79]:
y = np.array([1100, 1300, 800, 900, 1000, 1100])

In [85]:
w = (XTX_inv @ X.T) @ y

In [86]:
w

array([45.58076606,  0.42783519, 45.29127938])